#include "clipper.hpp"

void Clipper::_bind_methods() {

    ClassDB::bind_method(D_METHOD("get_version"), &Clipper::get_version);

    BIND_CONSTANT(INTERSECTION);
    BIND_CONSTANT(UNION);
    BIND_CONSTANT(DIFFERENCE);
    BIND_CONSTANT(XOR);

    BIND_CONSTANT(SUBJECT);
    BIND_CONSTANT(CLIP);

    BIND_CONSTANT(EVEN_ODD);
    BIND_CONSTANT(NON_ZERO);
    BIND_CONSTANT(POSITIVE);
    BIND_CONSTANT(NEGATIVE);

    BIND_CONSTANT(REVERSE_SOLUTION);
    BIND_CONSTANT(STRICTLY_SIMPLE);
    BIND_CONSTANT(PRESERVE_COLLINEAR);

    BIND_CONSTANT(SQUARE);
    BIND_CONSTANT(ROUND);
    BIND_CONSTANT(MITER);

    BIND_CONSTANT(CLOSED_POLYGON);
    BIND_CONSTANT(CLOSED_LINE);
    BIND_CONSTANT(OPEN_BUTT);
    BIND_CONSTANT(OPEN_SQUARE);
    BIND_CONSTANT(OPEN_ROUND);
}
